import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import { getOptionalUser, logout } from './server/session';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getOptionalUser();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-white dark:bg-gray-900 shadow-sm">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <nav className="flex justify-between h-16 items-center">
              <div className="flex items-center space-x-4">
                <Link
                  href="/"
                  className="text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-blue-400"
                >
                  Home
                </Link>
                {user ? (
                  <>
                    <span>{user.email}</span>
                    <form
                      action={async () => {
                        'use server';
                        await logout();
                      }}
                    >
                      <button type="submit">Logout</button>
                    </form>
                    <Link
                      href="/history"
                      className="text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-blue-400"
                    >
                      History
                    </Link>
                  </>
                ) : (
                  <>
                    <Link
                      href="/login"
                      className="text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-blue-400"
                    >
                      Login
                    </Link>
                    <Link
                      href="/register"
                      className="text-gray-700 dark:text-gray-200 hover:text-blue-600 dark:hover:text-blue-400"
                    >
                      Register
                    </Link>
                  </>
                )}
              </div>
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
